export default {
  factions: [
    {
      startupBuilding: 0,
      startupResources: [],
      uniqueBuildings: [],
      code: 0,
      name: "test_faction_0",
      displayName: "Test Faction 0",
      description: "Faction 0",
      img: "",
    },
    {
      startupBuilding: 0,
      startupResources: [],
      uniqueBuildings: [],
      code: 1,
      name: "test_faction_1",
      displayName: "Test Faction 1",
      description: "Faction 1",
      img: "",
    },
    {
      startupBuilding: 0,
      startupResources: [],
      uniqueBuildings: [],
      code: 2,
      name: "test_faction_2",
      displayName: "Test Faction 2",
      description: "Faction 2",
      img: "",
    },
  ],
  buildings: [
    {
      size: {
        x: 4,
        y: 4,
      },
      upgrade: -1,
      disabledGroundFlags: 2,
      fightingStats: {
        attack: {
          offense: 0,
          spy: 0,
        },
        defense: {
          offense: 0,
          spy: 0,
        },
      },
      allowTraining: false,
      allowSelling: true,
      isAvailable: false,
      resourceGains: [],
      costs: [
        {
          code: 0,
          quantity: 10000,
        },
      ],
      trainingGain: {
        code: 0,
        rate: 0,
        limit: 0,
        initialValue: 0,
      },
      level: 0,
      code: 0,
      name: "test_building_0",
      displayName: "Test Building 0",
      description: "Building 0",
      img: "",
    },
    {
      size: {
        x: 4,
        y: 4,
      },
      upgrade: -1,
      disabledGroundFlags: 2,
      fightingStats: {
        attack: {
          offense: 0,
          spy: 0,
        },
        defense: {
          offense: 0,
          spy: 0,
        },
      },
      allowTraining: false,
      allowSelling: true,
      isAvailable: false,
      resourceGains: [],
      costs: [
        {
          code: 0,
          quantity: 10000,
        },
      ],
      trainingGain: {
        code: 0,
        rate: 0,
        limit: 0,
        initialValue: 0,
      },
      level: 0,
      code: 1,
      name: "test_building_1",
      displayName: "Test Building 1",
      description: "Building 1",
      img: "",
    },
    {
      size: {
        x: 4,
        y: 4,
      },
      upgrade: -1,
      disabledGroundFlags: 2,
      fightingStats: {
        attack: {
          offense: 0,
          spy: 0,
        },
        defense: {
          offense: 0,
          spy: 0,
        },
      },
      allowTraining: false,
      allowSelling: true,
      isAvailable: false,
      resourceGains: [],
      costs: [
        {
          code: 0,
          quantity: 10000,
        },
      ],
      trainingGain: {
        code: 0,
        rate: 0,
        limit: 0,
        initialValue: 0,
      },
      level: 0,
      code: 2,
      name: "test_building_2",
      displayName: "Test Building 2",
      description: "Building 2",
      img: "",
    },
  ],
  resources: [
    {
      initialValue: 0,
      maxValue: 0,
      minValue: 0,
      useLimits: false,
      isDecimal: true,
      isPercent: false,
      isCurrency: false,
      code: 0,
      name: "gold",
      displayName: "Gold",
      description: "",
      img: "",
    },
    {
      initialValue: 0,
      maxValue: 0,
      minValue: 0,
      useLimits: false,
      isDecimal: true,
      isPercent: false,
      isCurrency: false,
      code: 1,
      name: "ruby",
      displayName: "Ruby",
      description: "",
      img: "",
    },
    {
      initialValue: 0,
      maxValue: 0,
      minValue: 0,
      useLimits: false,
      isDecimal: true,
      isPercent: false,
      isCurrency: false,
      code: 2,
      name: "soldiers",
      displayName: "Soldiers",
      description: "",
      img: "",
    },
    {
      initialValue: 0,
      maxValue: 0,
      minValue: 0,
      useLimits: false,
      isDecimal: true,
      isPercent: false,
      isCurrency: false,
      code: 3,
      name: "spies",
      displayName: "Spies",
      description: "",
      img: "",
    },
    {
      initialValue: 0,
      maxValue: 0,
      minValue: 0,
      useLimits: false,
      isDecimal: true,
      isPercent: false,
      isCurrency: false,
      code: 4,
      name: "attack_strength",
      displayName: "Attack strength",
      description: "",
      img: "",
    },
    {
      initialValue: 0,
      maxValue: 0,
      minValue: 0,
      useLimits: false,
      isDecimal: true,
      isPercent: false,
      isCurrency: false,
      code: 5,
      name: "defense_strength",
      displayName: "Defense strength",
      description: "",
      img: "",
    },
    {
      initialValue: 0,
      maxValue: 0,
      minValue: 0,
      useLimits: false,
      isDecimal: true,
      isPercent: false,
      isCurrency: false,
      code: 6,
      name: "spy_attack_strength",
      displayName: "Spy attack strength",
      description: "",
      img: "",
    },
    {
      initialValue: 0,
      maxValue: 0,
      minValue: 0,
      useLimits: false,
      isDecimal: true,
      isPercent: false,
      isCurrency: false,
      code: 7,
      name: "spy_defense_strength",
      displayName: "Spy defense strength",
      description: "",
      img: "",
    },
    {
      initialValue: 0,
      maxValue: 0,
      minValue: 0,
      useLimits: false,
      isDecimal: true,
      isPercent: false,
      isCurrency: false,
      code: 8,
      name: "total_spies",
      displayName: "Total spies",
      description: "",
      img: "",
    },
    {
      initialValue: 0,
      maxValue: 0,
      minValue: 0,
      useLimits: false,
      isDecimal: true,
      isPercent: false,
      isCurrency: false,
      code: 9,
      name: "hire_value",
      displayName: "Hire value",
      description: "",
      img: "",
    },
    {
      initialValue: 0,
      maxValue: 0,
      minValue: 0,
      useLimits: false,
      isDecimal: true,
      isPercent: false,
      isCurrency: false,
      code: 10,
      name: "max_plunder_bonus_to_allies",
      displayName: "Max plunder bonus to allies",
      description: "",
      img: "",
    },
    {
      initialValue: 0,
      maxValue: 0,
      minValue: 0,
      useLimits: false,
      isDecimal: true,
      isPercent: false,
      isCurrency: false,
      code: 11,
      name: "attack_bonus_to_allies",
      displayName: "Attack bonus to allies",
      description: "",
      img: "",
    },
    {
      initialValue: 0,
      maxValue: 0,
      minValue: 0,
      useLimits: false,
      isDecimal: true,
      isPercent: false,
      isCurrency: false,
      code: 12,
      name: "defense_bonus_to_allies",
      displayName: "Defense bonus to allies",
      description: "",
      img: "",
    },
    {
      initialValue: 0,
      maxValue: 0,
      minValue: 0,
      useLimits: false,
      isDecimal: true,
      isPercent: false,
      isCurrency: false,
      code: 13,
      name: "spy_attack_bonus_to_allies",
      displayName: "Spy attack bonus to allies",
      description: "",
      img: "",
    },
    {
      initialValue: 0,
      maxValue: 0,
      minValue: 0,
      useLimits: false,
      isDecimal: true,
      isPercent: false,
      isCurrency: false,
      code: 14,
      name: "spy_defense_bonus_to_allies",
      displayName: "Spy defense bonus to allies",
      description: "",
      img: "",
    },
    {
      initialValue: 0,
      maxValue: 0,
      minValue: 0,
      useLimits: false,
      isDecimal: true,
      isPercent: false,
      isCurrency: false,
      code: 15,
      name: "allies_total_cost",
      displayName: "Allies total cost",
      description: "",
      img: "",
    },
    {
      initialValue: 0,
      maxValue: 0,
      minValue: 0,
      useLimits: false,
      isDecimal: true,
      isPercent: false,
      isCurrency: false,
      code: 16,
      name: "attack_bonus_from_allies",
      displayName: "Attack bonus from allies",
      description: "",
      img: "",
    },
    {
      initialValue: 0,
      maxValue: 0,
      minValue: 0,
      useLimits: false,
      isDecimal: true,
      isPercent: false,
      isCurrency: false,
      code: 17,
      name: "defense_bonus_from_allies",
      displayName: "Defense bonus from allies",
      description: "",
      img: "",
    },
    {
      initialValue: 0,
      maxValue: 0,
      minValue: 0,
      useLimits: false,
      isDecimal: true,
      isPercent: false,
      isCurrency: false,
      code: 18,
      name: "spy_attack_from_allies",
      displayName: "Spy attack from allies",
      description: "",
      img: "",
    },
    {
      initialValue: 0,
      maxValue: 0,
      minValue: 0,
      useLimits: false,
      isDecimal: true,
      isPercent: false,
      isCurrency: false,
      code: 19,
      name: "spy_defense_from_allies",
      displayName: "Spy defense from allies",
      description: "",
      img: "",
    },
    {
      initialValue: 0,
      maxValue: 0,
      minValue: 0,
      useLimits: false,
      isDecimal: true,
      isPercent: false,
      isCurrency: false,
      code: 20,
      name: "attack_bonus",
      displayName: "Attack bonus",
      description: "",
      img: "",
    },
    {
      initialValue: 0,
      maxValue: 0,
      minValue: 0,
      useLimits: false,
      isDecimal: true,
      isPercent: false,
      isCurrency: false,
      code: 21,
      name: "attack_percentage_bonus",
      displayName: "Attack percentage bonus",
      description: "",
      img: "",
    },
    {
      initialValue: 0,
      maxValue: 0,
      minValue: 0,
      useLimits: false,
      isDecimal: true,
      isPercent: false,
      isCurrency: false,
      code: 22,
      name: "defense_bonus",
      displayName: "Defense bonus",
      description: "",
      img: "",
    },
    {
      initialValue: 0,
      maxValue: 0,
      minValue: 0,
      useLimits: false,
      isDecimal: true,
      isPercent: false,
      isCurrency: false,
      code: 23,
      name: "defense_percentage_bonus",
      displayName: "Defense percentage bonus",
      description: "",
      img: "",
    },
    {
      initialValue: 0,
      maxValue: 0,
      minValue: 0,
      useLimits: false,
      isDecimal: true,
      isPercent: false,
      isCurrency: false,
      code: 24,
      name: "spy_attack_bonus",
      displayName: "Spy attack bonus",
      description: "",
      img: "",
    },
    {
      initialValue: 0,
      maxValue: 0,
      minValue: 0,
      useLimits: false,
      isDecimal: true,
      isPercent: false,
      isCurrency: false,
      code: 25,
      name: "spy_attack_percentage_bonus",
      displayName: "Spy attack percentage bonus",
      description: "",
      img: "",
    },
    {
      initialValue: 0,
      maxValue: 0,
      minValue: 0,
      useLimits: false,
      isDecimal: true,
      isPercent: false,
      isCurrency: false,
      code: 26,
      name: "spy_defense_bonuse",
      displayName: "Spy defense bonuse",
      description: "",
      img: "",
    },
    {
      initialValue: 0,
      maxValue: 0,
      minValue: 0,
      useLimits: false,
      isDecimal: true,
      isPercent: false,
      isCurrency: false,
      code: 27,
      name: "spy_defense_percentage_bonus",
      displayName: "Spy defense percentage bonus",
      description: "",
      img: "",
    },
    {
      initialValue: 0,
      maxValue: 0,
      minValue: 0,
      useLimits: false,
      isDecimal: true,
      isPercent: false,
      isCurrency: false,
      code: 28,
      name: "plunder_pv_p_bonus",
      displayName: "Plunder pv pBonus",
      description: "",
      img: "",
    },
    {
      initialValue: 0,
      maxValue: 0,
      minValue: 0,
      useLimits: false,
      isDecimal: true,
      isPercent: false,
      isCurrency: false,
      code: 29,
      name: "plunder_pv_e_bonus",
      displayName: "Plunder pv eBonus",
      description: "",
      img: "",
    },
  ],
  commodities: [
    {
      target: 0,
      quantity: 0,
      purchaseLimit: 0,
      costs: [
        {
          code: 0,
          quantity: 10000,
        },
      ],
      items: [],
      code: 0,
      name: "test_commodity_0",
      displayName: "Test Commodity 0",
      description: "Commodity 0",
      img: "",
    },
    {
      target: 0,
      quantity: 0,
      purchaseLimit: 0,
      costs: [
        {
          code: 0,
          quantity: 10000,
        },
      ],
      items: [],
      code: 1,
      name: "test_commodity_1",
      displayName: "Test Commodity 1",
      description: "Commodity 1",
      img: "",
    },
    {
      target: 0,
      quantity: 0,
      purchaseLimit: 0,
      costs: [
        {
          code: 0,
          quantity: 10000,
        },
      ],
      items: [],
      code: 2,
      name: "test_commodity_2",
      displayName: "Test Commodity 2",
      description: "Commodity 2",
      img: "",
    },
  ],
  items: [
    {
      effectContext: 0,
      effects: [],
      effectDuration: 0,
      stackLimit: 1,
      code: 0,
      name: "test_item_0",
      displayName: "Test Item 0",
      description: "Item 0",
      img: "",
    },
    {
      effectContext: 0,
      effects: [],
      effectDuration: 0,
      stackLimit: 1,
      code: 1,
      name: "test_item_1",
      displayName: "Test Item 1",
      description: "Item 1",
      img: "",
    },
    {
      effectContext: 0,
      effects: [],
      effectDuration: 0,
      stackLimit: 1,
      code: 2,
      name: "test_item_2",
      displayName: "Test Item 2",
      description: "Item 2",
      img: "",
    },
  ],
  troops: [
    {
      fightingStats: {
        attack: {
          offense: 0,
          spy: 0,
        },
        defense: {
          offense: 0,
          spy: 0,
        },
      },
      code: 0,
      name: "test_troop_0",
      displayName: "Test Troop 0",
      description: "Troop 0",
      img: "",
    },
    {
      fightingStats: {
        attack: {
          offense: 0,
          spy: 0,
        },
        defense: {
          offense: 0,
          spy: 0,
        },
      },
      code: 1,
      name: "test_troop_1",
      displayName: "Test Troop 1",
      description: "Troop 1",
      img: "",
    },
    {
      fightingStats: {
        attack: {
          offense: 0,
          spy: 0,
        },
        defense: {
          offense: 0,
          spy: 0,
        },
      },
      code: 2,
      name: "test_troop_2",
      displayName: "Test Troop 2",
      description: "Troop 2",
      img: "",
    },
  ],
  grounds: [
    {
      flags: 1,
      generationType: 1,
      chance: 0.7,
      code: 0,
      name: "green",
      displayName: "Green",
      description: "Green ground",
      img: "",
    },
    {
      flags: 2,
      generationType: 1,
      chance: 0.2,
      code: 1,
      name: "water",
      displayName: "Water",
      description: "Water ground",
      img: "",
    },
  ],
  buildingUpgradePosts: [],
}
